[build]
  publish = "dist"
  command = "npm run build"

# ===================================
# LEGACY URL REDIRECTS (301 Permanent)
# ===================================
# These redirects handle old WordPress URLs and forward them to the new React app routes
# Must be placed BEFORE the catch-all SPA redirect

# Disclaimer/Transparency page -> Resources section
[[redirects]]
  from = "/full-transparency-disclaimer/"
  to = "/resources"
  status = 301
  force = true

[[redirects]]
  from = "/full-transparency-disclaimer"
  to = "/resources"
  status = 301
  force = true

# Contact page -> Support page
[[redirects]]
  from = "/contact/"
  to = "/support"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/support"
  status = 301
  force = true

# Client Portal -> Login page
[[redirects]]
  from = "/clients/"
  to = "/login"
  status = 301
  force = true

[[redirects]]
  from = "/clients"
  to = "/login"
  status = 301
  force = true

[[redirects]]
  from = "/client-portal/"
  to = "/login"
  status = 301
  force = true

[[redirects]]
  from = "/client-portal"
  to = "/login"
  status = 301
  force = true

# About page -> CMS About page
[[redirects]]
  from = "/about/"
  to = "/pages/about"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/pages/about"
  status = 301
  force = true

# Blog/Competitor 101 -> Resources section
[[redirects]]
  from = "/blog/"
  to = "/resources"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/resources"
  status = 301
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/resources"
  status = 301
  force = true

# ===================================
# SPA CATCH-ALL REDIRECT (Must be last)
# ===================================
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  # Environment variables are configured in Netlify dashboard for security
  # See NETLIFY_ENV_SETUP.md for configuration details

# Ensure all routes are handled by the SPA
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/events/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

# Add cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable Netlify Functions
[functions]
  directory = "netlify/functions"

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "payment=*, geolocation=(self), camera=(), microphone=(), fullscreen=*"
    # Enhanced CSP with reduced unsafe-inline usage
    # Note: Some unsafe-inline and unsafe-eval still required for Stripe and TinyMCE
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://maps.googleapis.com https://maps.gstatic.com https://www.google.com https://cdn.tiny.cloud https://*.tinymce.com https://js.hcaptcha.com https://*.hcaptcha.com https://www.googletagmanager.com https://*.google-analytics.com https://analytics.google.com blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tiny.cloud https://*.tinymce.com; img-src 'self' data: blob: https: https://images.unsplash.com https://*.unsplash.com https://images.pexels.com https://*.pexels.com https://maps.googleapis.com https://maps.gstatic.com https://sp.tinymce.com https://cdn.tiny.cloud https://www.google-analytics.com https://*.google-analytics.com https://analytics.google.com https://www.googletagmanager.com https://*.tile.openstreetmap.org https://tile.openstreetmap.org; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://nqvisvranvjaghvrdaaz.supabase.co wss://nqvisvranvjaghvrdaaz.supabase.co https://api.stripe.com https://maps.googleapis.com https://maps.gstatic.com https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.tiny.cloud https://*.tinymce.com https://nominatim.openstreetmap.org https://api.openai.com https://api.stability.ai https://hcaptcha.com https://*.hcaptcha.com https://api.ipify.org https://ipapi.co https://api.my-ip.io https://analytics.google.com https://www.google-analytics.com https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://region1.google-analytics.com https://region1.analytics.google.com; frame-src 'self' https://js.stripe.com https://www.google.com https://maps.google.com https://hcaptcha.com https://*.hcaptcha.com https://www.openstreetmap.org https://*.openstreetmap.org; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests"