# BMAD Method Configuration for Car Audio Events Platform
# Universal AI Agent Framework Integration

# Project metadata
project:
  name: "Car Audio Events Platform"
  type: "Full Stack Web Application"
  version: "1.26.123"
  description: "Car audio competition management platform with event management, payments, and AI agents"
  
# Agent team configuration
agents:
  core_team:
    - analyst
    - project_manager
    - architect
    - scrum_master
    - developer
    - qa
    
  specialized_team:
    - support_desk_specialist
    - event_platform_architect
    - payment_integration_specialist
    - database_architect
    - frontend_specialist
    - devops_engineer
    
# Development workflow
workflow:
  methodology: "Agile AI-Driven Development"
  sprint_duration: 14
  planning_phase: true
  context_engineering: true
  
# Technology stack
stack:
  frontend:
    - React
    - TypeScript
    - Tailwind CSS
    - Vite
  backend:
    - Supabase
    - PostgreSQL
    - Edge Functions (Deno)
  integrations:
    - Stripe
    - PayPal
    - Google Maps
    - OpenAI
    - Stability AI
    
# Domain expansion packs
expansion_packs:
  - event_management
  - payment_processing
  - email_automation
  - ai_generation
  
# AI integration settings
ai_settings:
  context_retention: true
  multi_agent_collaboration: true
  automated_testing: true
  code_review: true
  
# Project paths
paths:
  source: "./src"
  components: "./src/components"
  pages: "./src/pages"
  utils: "./src/utils"
  database: "./supabase"
  edge_functions: "./supabase/functions"
  documentation: "./docs"
  
# Security configuration
security:
  csrf_protection: true
  rate_limiting: true
  audit_logging: true
  rls_enabled: true
  
# Testing configuration
testing:
  manual_testing: true
  e2e_enabled: false
  unit_testing: false
  
# Deployment configuration
deployment:
  platform: "Netlify"
  auto_deploy: true
  branch: "main"
  edge_functions_platform: "Supabase"