name: Automated Security Maintenance

on:
  schedule:
    # Run daily at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no changes)'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  security-maintenance:
    name: Automated Security Fixes
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security maintenance
      id: security
      run: |
        if [[ "${{ github.event.inputs.dry_run }}" == "true" ]]; then
          npm run security:check
        else
          npm run security:maintain || true
        fi
        
        # Capture the exit code
        echo "exit_code=$?" >> $GITHUB_OUTPUT

    - name: Check for changes
      id: changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.changes.outputs.has_changes == 'true' && github.event.inputs.dry_run != 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          security: automated maintenance fixes
          
          - Fixed dependency vulnerabilities
          - Removed exposed secrets
          - Updated security configurations
          
          [Automated by security-maintenance workflow]
        branch: security/automated-fixes-${{ github.run_number }}
        delete-branch: true
        title: '🔒 Automated Security Fixes'
        body: |
          ## 🔒 Automated Security Maintenance
          
          This PR contains automated security fixes detected by our maintenance system.
          
          ### Changes Made:
          - ✅ Fixed npm dependency vulnerabilities
          - ✅ Removed hardcoded secrets
          - ✅ Updated security configurations
          - ✅ Added false positives to .secretsignore
          
          ### Security Report:
          See the attached security-report.json for details.
          
          ### Required Actions:
          1. Review all changes carefully
          2. If secrets were removed, rotate the exposed keys immediately
          3. Update environment variables in Netlify/Supabase as needed
          4. Test the application thoroughly
          
          ---
          *This PR was automatically generated by the security maintenance workflow.*
        labels: |
          security
          automated
          dependencies
        assignees: jryan2014

    - name: Upload security report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: security-report.json
        retention-days: 30

    - name: Send notification if critical issues
      if: steps.security.outputs.exit_code == '1'
      run: |
        echo "🚨 CRITICAL SECURITY ISSUES DETECTED!"
        echo "Exposed secrets were found and removed."
        echo "IMMEDIATE ACTION REQUIRED: Rotate all exposed keys!"
        # In production, this would send an email/Slack notification